backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Features, name: features, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Featured Items, name: featuredItems, widget: list, fields: [{label: Image, name: image, widget: image }, {label: Title, name: title, widget: string }, {label: Text, name: text, widget: text }, {label: Link, name: link, widget: string }, {label: Link Text, name: linkText, widget: string }]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Logo, name: logo, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Menu, name: scrollSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Scroll Items, name: scrollItems, widget: list, fields: [{label: Link, name: link, widget: string }, {label: Link Text, name: linkText, widget: string }]}]}
          - {label: How We Work, name: weWork, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Content, name: content, widget: markdown}, {link: Link, name: link, widget: string}]}
          - { label: Our Committee, name: ourCommittee, widget: object, fields: [{ label: Heading, name: heading, widget: string }, { label: Intro, name: intro, widget: markdown }, { label: Link, name: link, widget: string }, { label: Members, name: members, widget: list, fields: [{ label: Name, name: name, widget: string }, { label: Role, name: role, widget: string }, { label: Bio, name: bio, widget: text }, { label: Image, name: image, widget: image }, { label: Social, name: social, widget: list, fields: [{ label: Link, name: Link, widget: string }, { label: Source, name: source, widget: select, options: [{label: Twitter, value: twitter}, {label: Facebook, value: facebook}, {label: Instagram, value: instagram}]}]}]}]}
          - {label: School Testimonials, name: testimonialSection, widget: object, fields: [{ label: Heading, name: heading, widget: string }, { label: Intro, name: intro, widget: markdown }, { label: Link, name: name, widget: string }, { label: Testimonials, name: testimonials, widget: list, fields: [{ label: Quote, name: quote, widget: string }, { label: Source, name: source, widget: string }, { label: School, name: school, widget: string }]}]}
      - file: "src/pages/dental-students/index.md"
        label: "Dental Students"
        name: "dental-students"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Menu, name: scrollSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Scroll Items, name: scrollItems, widget: list, fields: [{label: Link, name: link, widget: string }, {label: Link Text, name: linkText, widget: string }]}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Position Name, name: name, widget: string}, {label: Text, name: text, widget: text}, {label: Link, name: link, widget: string}, {label: Button Text, name: buttonText, widget: string}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Content, name: content, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: markdown}, {label: Link, name: link, widget: string}]}]}
      - file: "src/pages/primary-schools/index.md"
        label: "Primary Schools"
        name: "primary-schools"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Menu, name: scrollSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Scroll Items, name: scrollItems, widget: list, fields: [{label: Link, name: link, widget: string }, {label: Link Text, name: linkText, widget: string }]}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Position Name, name: name, widget: string}, {label: Text, name: text, widget: text}, {label: Link, name: link, widget: string}, {label: Button Text, name: buttonText, widget: string}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Content, name: content, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: markdown}, {label: Link, name: link, widget: string}]}]}
      - file: "src/pages/parents-and-caregivers/index.md"
        label: "Parents and Caregivers"
        name: "parents-and-caregivers"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Menu, name: scrollSection, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Scroll Items, name: scrollItems, widget: list, fields: [{label: Link, name: link, widget: string }, {label: Link Text, name: linkText, widget: string }]}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Position Name, name: name, widget: string}, {label: Text, name: text, widget: text}, {label: Link, name: link, widget: string}, {label: Button Text, name: buttonText, widget: string}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Content, name: content, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: markdown}, {label: Link, name: link, widget: string}]}]}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
